apiVersion: v1
kind: Pod
metadata:
  name: jeu-allumettes
  labels:
    app: allumettes
    env: dev
spec:
  containers:
    - name: game
      image: ikl0934/jeu_allumettes:latest
      imagePullPolicy: Always
      stdin: true
      tty: true
      args: ["ibrahim@humain", "ordinateur@expert"]

      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"
        requests:
          memory: "128Mi"
          cpu: "100m"
  restartPolicy: Never